// =================================================================
// MEDIQUE - CENTRAL TRANSLATION SCRIPT (JAVASCRIPT ONLY)
// =================================================================

const translations = {
    'en': {
        // PatientDashboard.html
        'welcomeTitle': "🏥 Patient Dashboard", 'welcomeText': "Welcome, Kamal Perera", 'hospitalSelectTitle': "Select Hospital & Clinic", 'tokenStatusTitle': "Current Token Status", 'currentTokenLabel': "Current Token", 'waitTimeLabel': "Estimated Wait", 'queueLabel': "In Queue", 'alertsTitle': "SMS Alerts", 'smsStatusText': "SMS Notifications", 'smsDescription': "Get notified when your turn approaches", 'healthTipTitle': "💡 Health Tip of the Day", 'registerBtn': "Register New Token", 'manageBtn': "Manage Token",
        // RegisterToken.html
        'register.page.title': "Patient Dashboard", 'register.page.subtitle': "Easily register your token.", 'register.page.mainbutton': "Register New Token", 'register.modal.title': "Register New Token", 'register.step1.name': "Identification", 'register.step2.name': "Patient Details", 'register.step3.name': "Appointment", 'register.step4.name': "Confirmation", 'register.step1.title': "Step 1: Patient Identification", 'register.step1.label.mobile': "Mobile Number:", 'register.step1.helptext': "Enter your number and press 'Check'. If you are already registered, your details will be auto-filled.", 'register.step2.title': "Step 2: New Patient Details", 'register.step2.label.name': "Full Name:", 'register.step2.label.dob': "Date of Birth:", 'register.step2.label.gender': "Gender:", 'register.option.select': "Select...", 'register.option.male': "Male", 'register.option.female': "Female", 'register.option.other': "Other", 'register.step3.title': "Step 3: Appointment Details", 'register.step3.label.doctor': "Select Doctor:", 'register.step3.label.date': "Date:", 'register.step3.label.reason': "Reason for Visit (Briefly):", 'register.step4.title': "Step 4: Confirm Your Details", 'register.step4.label.name': "Patient Name:", 'register.step4.label.mobile': "Mobile Number:", 'register.step4.label.doctor': "Doctor:", 'register.step4.label.date': "Date:", 'register.step4.label.fee': "Fee:", 'register.step4.helptext': "Please review the information above and press 'Confirm & Register'.", 'register.button.previous': "Previous", 'register.button.next': "Next", 'register.button.submit': "Confirm & Register"
    },
    'si': {
        // PatientDashboard.html
        'welcomeTitle': "🏥 රෝගී පුවරුව", 'welcomeText': "ආයුබෝවන්, කමල් පෙරේරා", 'hospitalSelectTitle': "රෝහල සහ ක්ලිනික තෝරන්න", 'tokenStatusTitle': "වර්තමාන ටෝකනය තත්වය", 'currentTokenLabel': "වර්තමාන ටෝකනය", 'waitTimeLabel': "ඇස්තමේන්තුගත බලාසිටීම", 'queueLabel': "පෝලිමේ", 'alertsTitle': "SMS අනතුරු ඇඟවීම්", 'smsStatusText': "SMS දැනුම්දීම්", 'smsDescription': "ඔබේ වරය ළං වන විට දැනුම් දෙන්න", 'healthTipTitle': "💡 දිනයේ සෞඛ්‍ය උපදෙස", 'registerBtn': "නව ටෝකනයක් ලියාපදිංචි කරන්න", 'manageBtn': "ටෝකනය කළමනාකරණය කරන්න",
        // RegisterToken.html
        'register.page.title': "රෝගී පුවරුව", 'register.page.subtitle': "ඔබේ ටෝකනය පහසුවෙන් ලියාපදිංchi කරන්න.", 'register.page.mainbutton': "නව ටෝකනයක් ලියාපදිංචි කරන්න", 'register.modal.title': "නව ටෝකනයක් ලියාපදිංචි කරන්න", 'register.step1.name': "හඳුනාගැනීම", 'register.step2.name': "රෝගී විස්තර", 'register.step3.name': "වෙන්කරවා ගැනීම", 'register.step4.name': "තහවුරු කිරීම", 'register.step1.title': "පියවර 1: රෝගියා හඳුනාගැනීම", 'register.step1.label.mobile': "දුරකථන අංකය:", 'register.step1.helptext': "ඔබේ අංකය ඇතුළත් කර 'Check' ඔබන්න. ඔබ දැනටමත් ලියාපදිංචි වී ඇත්නම්, ඔබේ විස්තර ස්වයංක්‍රීයව පිරේ.", 'register.step2.title': "පියවර 2: නව රෝගී විස්තර", 'register.step2.label.name': "සම්පූර්ණ නම:", 'register.step2.label.dob': "උපන් දිනය:", 'register.step2.label.gender': "ස්ත්‍රී/පුරුෂ භාවය:", 'register.option.select': "තෝරන්න...", 'register.option.male': "පිරිමි", 'register.option.female': "ගැහැණු", 'register.option.other': "වෙනත්", 'register.step3.title': "පියවර 3: වෙන්කරවා ගැනීමේ විස්තර", 'register.step3.label.doctor': "වෛද්‍යවරයා තෝරන්න:", 'register.step3.label.date': "දිනය:", 'register.step3.label.reason': "පැමිණීමට හේතුව (කෙටියෙන්):", 'register.step4.title': "පියවර 4: ඔබේ විස්තර තහවුරු කරන්න", 'register.step4.label.name': "රෝගියාගේ නම:", 'register.step4.label.mobile': "දුරකථන අංකය:", 'register.step4.label.doctor': "වෛද්‍යවරයා:", 'register.step4.label.date': "දිනය:", 'register.step4.label.fee': "ගාස්තුව:", 'register.step4.helptext': "කරුණාකර ඉහත තොරතුරු සමාලෝචනය කර 'Confirm & Register' ඔබන්න.", 'register.button.previous': "පෙර", 'register.button.next': "ඊළඟ", 'register.button.submit': "තහවුරු කර ලියාපදිංචි වන්න"
    },
    'ta': {
        // PatientDashboard.html
        'welcomeTitle': "🏥 நோயாளி டாஷ்போர்டு", 'welcomeText': "வணக்கம், கமல் பெரேரா", 'hospitalSelectTitle': "மருத்துவமனை மற்றும் கிளினிக் தேர்வு", 'tokenStatusTitle': "தற்போதைய டோக்கன் நிலை", 'currentTokenLabel': "தற்போதைய டோக்கன்", 'waitTimeLabel': "மதிப்பிட்ட காத்திருப்பு", 'queueLabel': "வரிசையில்", 'alertsTitle': "SMS எச்சரிக்கைகள்", 'smsStatusText': "SMS அறிவிப்புகள்", 'smsDescription': "உங்கள் முறை நெருங்கும் போது அறிவிக்கப்படும்", 'healthTipTitle': "💡 நாளின் சுகாதார குறிப்பு", 'registerBtn': "புதிய டோக்கன் பதிவு செய்யவும்", 'manageBtn': "டோக்கன் நிர்வாகம்",
        // RegisterToken.html
        'register.page.title': "நோயாளி டாஷ்போர்டு", 'register.page.subtitle': "உங்கள் டோக்கனை எளிதாக பதிவு செய்யவும்.", 'register.page.mainbutton': "புதிய டோக்கன் பதிவு செய்யவும்", 'register.modal.title': "புதிய டோக்கன் பதிவு செய்யவும்", 'register.step1.name': "அடையாளம்", 'register.step2.name': "நோயாளி விவரங்கள்", 'register.step3.name': "நியமனம்", 'register.step4.name': "உறுதிப்படுத்தல்", 'register.step1.title': "படி 1: நோயாளி அடையாளம்", 'register.step1.label.mobile': "மொபைல் எண்:", 'register.step1.helptext': "உங்கள் எண்ணை உள்ளிட்டு 'Check' ஐ அழுத்தவும். நீங்கள் ஏற்கனவே பதிவு செய்திருந்தால், உங்கள் விவரங்கள் தானாக நிரப்பப்படும்.", 'register.step2.title': "படி 2: புதிய நோயாளி விவரங்கள்", 'register.step2.label.name': "முழு பெயர்:", 'register.step2.label.dob': "பிறந்த தேதி:", 'register.step2.label.gender': "பாலினம்:", 'register.option.select': "தேர்ந்தெடுக்க...", 'register.option.male': "ஆண்", 'register.option.female': "பெண்", 'register.option.other': "மற்றவை", 'register.step3.title': "படி 3: நியமன விவரங்கள்", 'register.step3.label.doctor': "மருத்துவர் தேர்வு:", 'register.step3.label.date': "தேதி:", 'register.step3.label.reason': "வருகைக்கான காரணம் (சுருக்கமாக):", 'register.step4.title': "படி 4: உங்கள் விவரங்களை உறுதிப்படுத்தவும்", 'register.step4.label.name': "நோயாளியின் பெயர்:", 'register.step4.label.mobile': "மொபைல் எண்:", 'register.step4.label.doctor': "மருத்துவர்:", 'register.step4.label.date': "தேதி:", 'register.step4.label.fee': "கட்டணம்:", 'register.step4.helptext': "தயவுசெய்து மேலே உள்ள தகவலை மதிப்பாய்வு செய்து 'Confirm & Register' ஐ அழுத்தவும்.", 'register.button.previous': "முந்தைய", 'register.button.next': "அடுத்தது", 'register.button.submit': "உறுதிசெய்து பதிவுசெய்"
    }
};

function changeLanguage(langCode) {
    if (!langCode) return;
    localStorage.setItem('preferredLanguage', langCode);
    applyTranslations(langCode);
}

function applyTranslations(langCode) {
    const langPack = translations[langCode] || translations['en'];
    $('.language-btn').removeClass('active');
    $(`.language-btn[data-lang='${langCode}']`).addClass('active');
    $('[data-translate-key]').each(function() {
        const key = $(this).data('translate-key');
        if (langPack[key]) {
             $(this).text(langPack[key]);
        }
    });
    $(document).trigger('languageChange', langCode);
}

$(document).ready(function() {
    $('.language-btn').on('click', function() {
        const langCode = $(this).data('lang');
        changeLanguage(langCode);
    });
    const preferredLanguage = localStorage.getItem('preferredLanguage') || 'en';
    applyTranslations(preferredLanguage);
});